#!/usr/bin/python
import argparse
import os

import jinja2
import yaml

from run_tools.build_website import BuildWebsite


def run_task(task):
    for dep_task in task.get_dependencies():
        run_task(dep_task)
    task.run()


def load_config(config_file):
    with open(config_file) as fp:
        return yaml.load(fp)


if __name__ == '__main__':
    root_dir = os.path.dirname(os.path.realpath(__file__))
    config_path = os.path.join(root_dir, 'config.yaml')
    build_dir = os.path.join(root_dir, '_build')
    static_dir = os.path.join(root_dir, 'static')
    photos_dir = os.path.join(root_dir, 'photos')
    template_dir = os.path.join(root_dir, 'templates')

    config = load_config(config_path)

    templateLoader = jinja2.FileSystemLoader(searchpath=template_dir)
    template_env = jinja2.Environment(loader=templateLoader)

    run_task(BuildWebsite(config, static_dir, photos_dir, build_dir, template_env))

